version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
      - yarn install --frozen-lockfile --verbose

  pre_build:
    commands:
      # Build React frontend
      - cd frontend
      - yarn build

  build:
    commands:
      # Build Node.js backend
      - cd ../backend
      - npm install
      - npm run build

artifacts:
  files:
    - frontend/build/**/*
    - backend/dist/**/*
    - backend/package.json
    - backend/package-lock.json

cache:
  paths:
    - node_modules/**/*
